### PR TITLE
Fix Bug #36

### PR DESCRIPTION
**Pull request by cristiancedenogallego**
Fix Bug #36

### CODE REVIEW

**Comment by fabriziomoscon** [comment]
I also needed to fix this.
But I have decided to allow to pass an entire props object for the ScrollView, so if the component becomes more extensible:

https://github.com/fabriziomoscon/react-native-modal-picker/commit/8fc83dfa52fecec94506d6de4ac0ff8fcb06901e

**Comment by adrai** [comment]
Hi @fabriziomoscon I'm trying to temporary use your fork... Did you try with RN 0.42 ? seems like the modal is not opening :-(

**Comment by fabriziomoscon** [comment]
uhmmm,
haven't tried yet

**Comment by adrai** [comment]
I'm going to try https://github.com/Ario-Inc/react-native-modal-picker by @wdimmit too

**Comment by adrai** [comment]
same with that fork :-(

**Comment by adrai** [comment]
possible issuee: https://github.com/facebook/react-native/issues/12515

**Comment by adrai** [comment]
ok, seems to be a react-native issue: solved here => https://github.com/facebook/react-native/issues/12223

**Pull request closed without merging**
