### PR TITLE
Portal removal for RN0.26+

### PR DESCRIPTION
**Pull request by rajkissu**
Removes portal.js dependency as it's not included in RN0.26+

### CODE REVIEW

**Comment by ararog** [comment]
I would like to have a new release with this change, but I'm afraid that I have to fork to use it.

**Comment by caroaguilar** [comment]
Need this to be merged please!!

**Comment by ararog** [comment]
@rajkissu did you have a fork with these changes?

**Comment by d-a-n** [comment]
@rajkissu Thanks a lot 👍

**Pull request merged**
